import type { Metadata } from "next";
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import Container from "@mui/material/Container";
import "./globals.css";
import { auth } from "auth";
import { Providers } from "./components/providers";

export const metadata: Metadata = {
  title: "SIMPLE_TPV",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();
  return (
      <Providers session={session}>
        <html lang="es">
          <body>
            <Container maxWidth="sm">              
              {children}
            </Container>
          </body>
        </html>
      </Providers>
  );
}
