import type { Metadata } from "next";
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import Container from "@mui/material/Container";
import DenseAppBar from "./components/appMenuBar"

export const metadata: Metadata = {
  title: "SIMPLE_TPV",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body>
        <Container maxWidth="sm">
          <DenseAppBar />
          {children}
          </Container>
      </body>
    </html>
  );
}
